# -*- coding: utf-8 -*-
"""1_cycle1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EACKbjvjTg6o0jCI9ovL_A4irVcJvU9l
"""

#    Develop a program to read a four-digit number and find its
# a. Sum of digits
# b. Reverse
# c. Difference between the product of digits at the odd position and the product of digits at the even position.

num=int(input('Enter a 4 digit number'))   # taking input from user
temp=num                                   # assining value of sum to temp variable
sum=0                                      # assining 0 to sum                                   
revnum=0
evn=1
odd=1
x=temp%10                                  # to get unit digit 
sum=sum+x                                  # taking sum of digits
revnum=(revnum*10)+x                       # storing individual digits in reverse order
evn=evn*x                                  # stroring even position digit
temp=temp//10                              # intiger divition by 10 to get quoient
x=temp%10
sum=sum+x
revnum=(revnum*10)+x
odd=odd*x                                  # stroring odd posiotion digit
temp=temp//10
x=temp%10
sum=sum+x
revnum=(revnum*10)+x
evn=evn*x                                  # taking product of even postion numbers                                 
temp=temp//10
x=temp%10
sum=sum+x
revnum=(revnum*10)+x
odd=odd*x                                  # taking product of odd position numbers
temp=temp//10
diff=odd-evn                               # difference of odd position product and even position product
print('Sum : ',sum)                        # printing sum of digit
print('Reverse number : ',revnum)          # printing reverse number
print('Difference between the product of digits at the odd position and the product of digits at the even position : ',diff)  # printing product difference