# -*- coding: utf-8 -*-
"""2_cycle1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TtJiHwMyeexe-UKeyW7FEeOxkzdH8zjE
"""

# Develop a program to read the three sides of two triangles and calculate the area of both. Define a function to read the three sides and call it.
# Also, define a function to calculate the area. Print the totalarea enclosed by both triangles and each triangle's contribution (%) towards it.

def getdata():     # function to read triangles side
  a=int(input("Enter the first side of triangle : "))
  b=int(input("Enter the second side of Triangle : "))
  c=int(input("Enter the third side of Triangle : ")) 
  return a,b,c

def area():       # function to calculate area of triangle
  a, b, c= getdata()
  s=(a+b+c)/2
  ar=(s*(s-a)*(s-b)*(s-c))**0.5
  return ar

a1=area()        # assigning area of triangle 1
a2=area()        # assigning area of triagle 2
print('Total area of 2 triangles : ', a1+a2)  # printing total area
con1=(a1/(a1+a2))*100                         # area contribution of triangle 1
con2=(a2/(a1+a2))*100                         # area contribution of triangle 2
print('Contribution of triangle 1 : ',con1)   
print('Contribution of triangle 2 : ',con2)