# -*- coding: utf-8 -*-
"""3_cycle2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I3a7kFOEBp5B8xYEOi4NeAycX_BrxMDY
"""

a = open("iris.json","r")             #reading the file iris.json
b = a.readlines()                     #a list having each line of the file as an element
#print(b)                   
import json
a = open("iris.json","r")
dictionary = json.load(a)             #Convert into dictionary objects.
dictionary1 = dictionary
a.close()
#print(dictionary)
#[print(i['species']) for i in dictionary]
for i in dictionary:               
  if i['species'] == 'setosa':        #printing the details of all flowers whose species is "setosa".
    print(i)

l_species = []
for i in dictionary:                  #forming a list of type of species
  if i['species'] not in l_species:
    l_species.append(i['species'])
#print(l_species)

l_area_sepal1 = []
l_area_petal1 = []
l_area_sepal2 = []
l_area_petal2 = []
l_area_sepal3 = []
l_area_petal3 = []

for i in dictionary1:
  ptlarea = (i['sepalLength']*i['sepalWidth'])  #calculating petal area of each flower 
  splarea = (i['petalLength']*i['petalWidth'])  #calculating sepel area of each flower
  totalarea = ptlarea + splarea                 #calculating total area of each flower       
  i.update({'totalArea' : totalarea})           #adding total area to the dictionary
  if i['species'] == l_species[0]:
    l_area_sepal1.append(i['sepalLength']*i['sepalWidth'])      
    l_area_petal1.append(i['petalLength']*i['petalWidth'])
  elif i['species'] == l_species[1]:                                 #calculating sepal and petal area of different species
    l_area_sepal2.append(i['sepalLength']*i['sepalWidth'])
    l_area_petal2.append(i['petalLength']*i['petalWidth'])
  elif i['species'] == l_species[2]:
    l_area_sepal3.append(i['sepalLength']*i['sepalWidth'])
    l_area_petal3.append(i['petalLength']*i['petalWidth'])


# print(l_area_sepal1)
# print(l_area_petal1)
# print(l_area_sepal2)
# print(l_area_sepal2)
# print(l_area_sepal3)
# print(l_area_sepal3)

print(l_species[0])
print("Greatest sepal area : ",max(l_area_sepal1))                
print("Minimum petal area  : ",min(l_area_petal1))                
print(" ")                                                   
print(l_species[1])                                                #printing the max sepal and minimum petal area of different species
print("Greatest sepal area : ",max(l_area_sepal2))
print("Minimum petal area  : ",min(l_area_petal2))
print(" ")
print(l_species[2])
print("Greatest sepal area : ",max(l_area_sepal3))
print("Minimum petal area  : ",min(l_area_petal3))

print(dictionary1)
sortedDictionary = (sorted(dictionary1, key = lambda i:i['totalArea'] ))   #Sort the list of dictionaries according to the total area of sepal and petal
print(sortedDictionary)