# -*- coding: utf-8 -*-
"""4_cycle2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WlZQEfZ-PHZ8-7lwzE6021tOsOHAPYfw
"""

class Box:
  __length = None
  __breadth = None
  __height = None
  __area = None
  __volume = None

  def __init__(self, *p):
    if len(p) == 1:
      self.__length = p[0]
      self.__breadth = p[0]
      self.__height = p[0]
    elif len(p) == 2:
      self.__length = p[0]
      self.__breadth = p[0]
      self.__height = p[1]
    elif len(p) == 3:
      self.__length = p[0]
      self.__breadth = p[1]
      self.__height = p[2]

  def volume(self):
    self.__volume = self.__length*self.__breadth*self.__height

  def area(self):
    self.__area = 2*(self.__length*self.__length + self.__breadth*self.__breadth + self.__height*self.__height)

  def display(self):
    print("Box Details")
    print("Length  = ",self.__length)
    print("Breadth = ",self.__breadth)
    print("Height  = ",self.__height)
    print("Area    = ",self.__area)
    print("Volume  = ",self.__volume)

  def ratio(self):
    r= (self.__volume)/(self.__area)
    return r

import random

n=int(input("Enter the number of objects that want to made : "))
ls1 = []
count=0
for i in range(0,n,3):
  while(count!=n):
    ls1.insert(i,Box(random.randrange(1,50,1)))
    count = count+1
    ls1.insert(i+1,Box(random.randrange(1,50,1),random.randrange(1,50,1)))
    count = count+1
    ls1.insert(i+2,Box(random.randrange(1,50,1),random.randrange(1,50,1),random.randrange(1,50,1)))
    count = count+1
    break;

for i in range(0,n):
  ls1[i].area()
  ls1[i].volume()

ls2 = []

for i in range(0,n):
  ls2.append(ls1[i].ratio())
  ls1[i].display()
  print("Ratio   : ",ls1[i].ratio())
  print(" ")
  
for i in range(0,n):
  if max(ls2) == ls1[i].ratio():
    print(" ")
    ls1[i].display()
    print("Greatest Ratio",ls1[i].ratio())